resourceDir = "../resources"
theme = "ananke"
SectionPagesMenu = "main"
DefaultContentLanguage = "en"
baseURL = "https://web.hugity.com/j570299q7zhgtpmtqpsdsqjjy57qk4v7/"
languageCode = "en-us"
title = ""
enableRobotsTXT = true
googleAnalytics = ""

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "assets"

[params]
favicon = ""
site_logo = ""
text_color = ""
background_color_class = ""
recent_posts_number = 3
author = ""
description = ""

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[pagination]
pagerSize = 3

[languages]
[languages.en]
contentDir = "content/en"
weight = 1
title = ""

[languages.fr]
contentDir = "content/fr"
title = "Ananke Fr"
weight = 2

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5